### 회원 가입
POST http://localhost:8080/api/v1/auth/signup
Content-Type: application/json

{
  "nickname": "12345",
  "email": "12345@naver.com",
  "year": 1998,
  "month": 12,
  "day" : 12,
  "gender" : "MAN",
  "password": "Abc123!!"
}

### 로그인
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "12345@naver.com",
  "password": "Abc123!!"
}