spring:
  redis:
    host: localhost
    port: 6379

  main:
    allow-bean-definition-overriding: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  rabbitmq:
    host: localhost
    port: 5672
    username: ENC(pp/42mURRq0LfR/mLK2cGw==)
    password: ENC(iun1uKrWqwmNCepO/c2oPfmdv67jlkp5)
    template:
      default-receive-queue: ENC(T7RGsRiCT6AuAF0SvTaaWSyfKomggc6a)
      exchange: ENC(Szepsb+4rxFhAd8SP4IBaaULlQAjam0ayyHkxV+WAk0=)
      routing-key: ENC(wLbF0pY7LMiizRg+l0MUi1Kbhl8smMDK)

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(rshExAmjBc5kYu6uqVOE2GLLFtuODhG49kHSnqqn+jwVN3hu8yZt5NhKwkqWL3924wUAo80OwVrvQJ4n/BD8T6gkHroDnjjxCNfOi2VW/v8=)
            client-secret: ENC(NNHnN8yaKo6IMLgJ5U0ZZG3a/0UXdnh2SAajwOuXyIN10JrseFh9Sa2d6e7wZGN3)
            redirect-uri: ENC(xahjgyE04NRL/2wFNXr6zmKHfAnQIsAnSLxfP5VLkh3aMC0MUWChuVeFsEPodmdJr2gVxY2jkr4=)
            scope: openid,profile,email
          kakao:
            client-id: ENC(zXaLrbeCrBLZx+6pS6ZsDjDVgHU4RgCqNnr5BEwy4kIs3I/VQMkpuxE6h1WMdoNq)
            client-secret: ENC(M1psFBk0ldsjxqCuqGZK6r5ilFlZZYdY8wwO5CJwvhkLvCCyIePIemLcq/GTlLT/)
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: villager-app
            redirect-uri: ENC(r+g4MWAVXpjaGF1NDRrwZj/EsBEAwH1Ub9yuSWA4t0ma2rwaplD4f+Vnb4S1aeBUTRgXU7R/1rA=)
            scope: openid,profile_nickname,profile_image,account_email
            provider: kakao
          naver:
            client-id: ENC(r+UgAPMadEoJEyIKDM93b9FHFjkr4nOs8gZghWX47FM=)
            client-secret: ENC(YpIeX1xiNDblTKg0yQ68p0vdYno0iyFg)
            authorization-grant-type: authorization_code
            client-name: villager-app
            redirect-uri: ENC(CRxuBHQfARbr8yYPkkGdV2j8tmeRrbHTzLsgzy4X8OfqCyTRF44wJO/TPoMvyHQeyuFTs3wL3bw=)
            scope: profile,email
            provider: naver
        provider:
          kakao:
            issuer-uri: https://kauth.kakao.com
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  mail:
    host: smtp.gmail.com
    port: 587
    username: villagerservice@gmail.com
    password: uqyrsuhdldhaflax
    properties:
      mail:
        smtp:
          starttls:
            enable: true

jwt:
  secret: ENC(fkuG48QRwRmKSmFQfVDWnOSxW5d1npLCTx7zoiW2QLqejqEec4nOb5B61ck3xcbUnkRbTRDVwBym4Z4WE7r+Zw==)
  access-token-validity-in-seconds: 600000
  refresh-token-validity-in-seconds: 86400000  # 24 * 60 * 60 * 1000 = 86400000

cors:
  allowed-origins: http://localhost:3000, http://ec2-15-164-233-107.ap-northeast-2.compute.amazonaws.com:8080, https://devwinter.com, https://clinquant-mochi-13e034.netlify.app
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
  allowed-headers: '*'
  max-age: 3600

oauth2:
  authorizedRedirectUris:
    - http://localhost:3000/oauth2/redirect
    - https://clinquant-mochi-13e034.netlify.app/oauth2/redirect

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

cloud:
  aws:
    s3:
      bucket: friend-bucket
    credentials:
      access-key: ENC(wpDFgrOB4WqW3m2Jbe/8uh53fXG6XptMWOWUA/eSaDE=)
      secret-key: ENC(DzjJApwlNxv0qlnuOjDc96YSGXRHHzPC1JMWtG9ai68+lbCrNtpsTEIHyUGZVsiAk9jGeJ0tQ64=)
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

aws:
  s3:
    base-url: ENC(9SFg52vMZB3/L9JIWV4hHioqba7mr/LGrC5/q/cCy7EGunaXOn+ixxCsl1W7ipo1HBv6PEiKDnDlOeaqse8I/w==)

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR
---
spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always
      data-locations: classpath*:database/local/data.sql

jwt:
  active: true
---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ENC(5H5007IA8s4nlJ/OEpn9aiZreBVxAIJ70gPj4VvQLesEyUAF1pAuOMTAIUkgEgYAmh+/ABAxdARBz91n2Q7eV6y9+L0AW+Fc+YH3aVH84UcIXCi5za+DERcjaiTRLGSV)
    username: ENC(GMN8y+n+DmkYss8RKwKZ7A==)
    password: ENC(tE4gxhWYPayeL3wSJEWb/+DNSoi3POVW)

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

---
spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: false
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: town-test
  h2:
    console:
      enabled: false
      path: /h2-console

  datasource:
    url: ENC(pOKkBrx4n4fz36fwyach9j4BHH8SzKpkybSrCWz3lD+VhO42jDe+PicxKEO76XYw)
    username: ENC(wAt74LBXAmDPVdksRu4Bzvje20PNlXFU)
    password: ENC(ztBSYtdJzQ+bUIktdJD0emCxQrHbABxR)

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
jwt:
  active: true

